version: "3"

services:
#master
  master:
    image: jenkins/jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./jenkins_home:/var/jenkins_home
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
#agent
  agent:
    image: jenkins/ssh-agent
    # ports:
    #   - "2222:22"
    volumes:
      - ./jenkins_agent_home:/home/jenkins
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16